version: '3'
services:
    app:
      build: .
      env_file:
        - ./settings.env
      volumes:
        - ".:/home/docker"
      depends_on:
        - db

    db:
      env_file:
        - ./settings.env
      image: "postgres:alpine"
      ports:
        - "5432:5432"
      volumes:
          - "./env/db:/var/lib/postgresql/data"

    proxy:
        image: "nginx:alpine"
        ports:
          - "80:80"
        volumes:
          - "./static:/usr/share/nginx/html/static"
          - "./nginx.conf:/etc/nginx/nginx.conf"
          - "./logs/proxy:/var/log/nginx"
        depends_on:
          - app
    radius:
      image: "freeradius/freeradius-server:3.0.19-alpine"
      volumes:
        - "./radius:/etc/freeradius"
      depends_on:
        - db
        - app
