version: '3'
services:
    app:
      build: .
      volumes:
        - ".:/home/docker"

    db:
      image: "postgres:latest"
      ports:
        - "5432:5432"
      volumes:
          - "./env/db:/var/lib/postgresql/data"

    proxy:
        image: "nginx:alpine"
        ports:
          - "80:80"
        volumes:
          - "./static:/usr/share/nginx/html/static"
          - "./nginx.conf:/etc/nginx/nginx.conf"
